// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotesLogin.Models;

public partial class Note
{
    public int NoteId { get; set; }

    public string NoteTitle { get; set; }

    public string NoteText { get; set; }

    public DateOnly NoteDate { get; set; }

    public bool NotePublic { get; set; }

    public string NoteUserIdFk { get; set; }
}